In [2]:
import numpy as np

org_array = np.array([3,1,9, 5])
sort_array1 = np.sort(org_array)
print(sort_array1)

[1 3 5 9]


In [5]:
# 내림차순 정력
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


In [7]:
array2d = np.array([[8,12],
                   [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis = 0)
print(sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print(sort_array2d_axis1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [8]:
# 원본 행렬이 정렬되었을때 기존 원본 행렬의 원소에 대한 인덱스 값
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(sort_indices)

<class 'numpy.ndarray'>
[1 0 3 2]


In [9]:
name_array = np.array(["John", "Mike", "Sarah", "Kate", "Samuel"])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print(sort_indices_asc)
print(name_array[sort_indices_asc])

[0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
